"""Add youtube_url to Content

Revision ID: 0f5d4db2d672
Revises: 09c9c21d7b43
Create Date: 2024-09-20 16:05:20.479324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5d4db2d672'
down_revision = '09c9c21d7b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('youtube_url')

    # ### end Alembic commands ###
